name: Deploy Blazor WASM project to Github Pages
  
on:
  workflow_dispatch:
  push:
    branches: main
    paths: ./Ecommerce_Blazor/**

env:
  PROJECT_NAME: Ecommerce_Blazor
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setting up .NET environment
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'

      - name: Building project
        run: dotnet publish ./${{ env.PROJECT_NAME }}/${{ env.PROJECT_NAME }}.csproj -o release
        
      - name: Changing base-tag in index.html
        run: sed -i 's/<base href="\/" \/>/<base href="\/Ecommerce\/" \/>/g' release/wwwroot/index.html
        
      - name: Deploying to Pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./release/wwwroot
